name: simplest_document_scanner
description: "Simplest document scanning plugin powered by VisionKit on iOS and MLKit on Android"
version: 1.0.1
repository: https://github.com/sunderee/simplest-document-scanner

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: '>=3.38.2'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.bizjak.simplest_document_scanner
        pluginClass: SimplestDocumentScannerPlugin
      ios:
        pluginClass: SimplestDocumentScannerPlugin